name: balanced_parentheses_dart_3
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/shilangyu/balanced_parentheses_dart_3

environment:
  sdk: ^3.0.0-417.3.beta

dependencies: {}

dev_dependencies: {}
